### ISSUE TITLE
Split test suit to run them faster

### ISSUE THREAD

**Issue by lpfister** [plu/parallel_ios_tests#1]
Hello,

First of all, AWESOME! just tried it, love it! really cool.

I had one questions, would it be somehow possible to split test suite per device, in order to run all test fast.
--> Instead of running all test 1-100 to 2 devices, run 1-50 and 51-100 at the same time?

Would be really cool for CI

Thanks and advance, and again awesome work !

Cheers,
Loic

**Comment by oliverhu** [comment]
@lpfister +1 !!!

**Comment by oliverhu** [comment]
@lpfister  you can pass in -only SomeTestTarget

Refer to the Read.me of https://github.com/facebook/xctool

**Comment by plu** [comment]
Yep, that should do the trick. If you create a few simulators using `simctl` and then spawn a couple of threads passing different `-only` arguments, it should do what you expect.

`    -only SPEC                 SPEC is TARGET[:Class/case[,Class2/case2]]; use * when specifying class or case prefix.`

**Comment by plu** [comment]
`xctool` based solution is deprecated, closing this issue because of that fact.
