### ISSUE TITLE
How to run sampleApp target and run multi simulators simultaneously 

### ISSUE THREAD

**Issue by allentofight** [plu/parallel_ios_tests#10]
Using  KIF  works well ,but now I want it to run on the "sampleApp" target,and control app woking `manually` on multi simulators ,how to do it?

**Comment by allentofight** [comment]
Maybe I don't say it clearly ,what I mean is I want to run the main target on multi simulators,and after they launch,I control the app by myself,not like the KIF automatically running

**Comment by plu** [comment]
Try to play around with `xcrun simctl install` and `xcrun simctl launch`. Pull requests on https://github.com/plu/simctl to support that are welcome :).

**Comment by allentofight** [comment]
Cool!
