### ISSUE TITLE
rake test['SampleApp'] failed

### ISSUE THREAD

**Issue by allentofight** [plu/parallel_ios_tests#11]
It only support run testTarget? I want to launch the SampleApp in multi Simulators
But when I run 

```shell
rake test['SampleApp']
```
multi simulators launched ,but it reports the following error

```shell
ERROR: run-tests: 'SampleApp' is not a testing target in this scheme.
```

how to run the `SampleApp` target(not the SampleAppTest target) in multi simulators in your example?

**Comment by plu** [comment]
Try SampleAppTests instead?

**Comment by allentofight** [comment]
work on SampleAppTests is good,But I want to run on SampleApp in multi simulators,can't it support it?

**Comment by plu** [comment]
Not supported, sorry.

Try to play around with xcrun simctl install and xcrun simctl launch. Pull requests on https://github.com/plu/simctl to support that are welcome :).

**Comment by plu** [comment]
I added support for installing and launching to the `simctl` gem now. Here's an example `rake` task how to use it: https://github.com/plu/parallel_ios_tests/commit/0fd27b3aaba38113c876612a30bf8d972817012c

**Comment by allentofight** [comment]
@plu Thank you for your response,But when I execute

```shell
rake launch
```

**Comment by plu** [comment]
`bundle install`

**Comment by allentofight** [comment]
It works! Thank you very much!

**Comment by allentofight** [comment]
Is it possible to manually control multi simulators in sync 

for example:

`when I click the row in tableView in one simulator,the other simulator also do the same thing`

 I don't want to use the automatically tools like KIF etc.I just want to do the operation by my self,It would be great if the simulators can in sync on my operation

**Comment by plu** [comment]
I don't think so.

**Comment by plu** [comment]
You have a few options though, KIF, UIAutomation, Xcode UI Tests...

**Comment by allentofight** [comment]
Yeah,These automation options is great,but I wish I can manually control multiple simulators , anyway, thanks for your advice
