### ISSUE TITLE
Switch to `xcodebuild test-without-building` instead of xctool

### ISSUE THREAD

**Issue by bgerstle** [plu/parallel_ios_tests#12]
New in Xcode 8, xcodebuild has a `test-without-building` and `build-without-testing` commands might be used to spawn multiple test runs targeting multiple destinations. It might be worth using the new `xctestrun` manifest file as well (see `man xcodebuild.xctestrun`).

**Comment by plu** [comment]
Thanks for bringing this up. I have tried to run `test-without-building` with two different destinations in two different terminals at the same time, unfortunately that does not seem to work, they get in the way of each other. I havn't figured out how to use `-xctestrun` properly, yet.

However `build-without-testing` is a great advancement, now it's possible to use that in combination with `FBSimulatorControl` (which can launch the tests on different destinations in parallel. If I find some time, I will create another example using this.

**Comment by ollieatkinson** [comment]
@plu have you had any luck/advancements on this yet? `build-without-testing` doesn't seem to generate a `xctestrun`. This would be really great.

**Comment by plu** [comment]
I have updated the example project here and provided a new tool to achieve what you suggested:

https://github.com/plu/pxctest
