### ISSUE TITLE
Does this work with Fastlane's scan?

### ISSUE THREAD

**Issue by kleinlieu** [plu/parallel_ios_tests#3]
Hey there, 

Would this work in conjunction with Fastlane's scan tool, which just wraps around xcodebuild? Or is it meant to be used exclusively with xctool? Thanks! https://github.com/fastlane/scan

**Comment by plu** [comment]
Unfortunately I didn't find a way to make it work with the plain `xcodebuild`, so yes, `xctool` is required right now.

**Comment by kleinlieu** [comment]
Thanks! Closing!
