### ISSUE TITLE
Simulators grows more and more

### ISSUE THREAD

**Issue by DaidoujiChen** [plu/parallel_ios_tests#4]
Hello @plu,

If we named different simulators name for different projects and we do not delete them.
There are more and more simulators in the list
![2016-02-23 10 47 55](https://cloud.githubusercontent.com/assets/670441/13240172/4cc6d440-da1b-11e5-85dc-c392eda44a05.png)
Is it necessary to use `devices.each { |device| device.delete! }` after threads finish to clean up simulators for testing?

**Comment by plu** [comment]
It's up to you if you want to delete them after the test run :). However this line makes sure that the Simulator with the same name is deleted and created again (no duplicates):

https://github.com/plu/parallel_ios_tests/blob/master/Rakefile#L19

**Comment by plu** [comment]
Update `simctl`, then change your code to something like this:
https://github.com/plu/parallel_ios_tests/commit/c5d1d589b227ef5b51330327a25a770a7fdf15a0

**Comment by DaidoujiChen** [comment]
:+1: 
thank you
