### ISSUE TITLE
UI Tests support

### ISSUE THREAD

**Issue by SukhotinM** [plu/parallel_ios_tests#5]
Hello! thanks, thats a great thing. 
I just have a question: does this support UI Testing framework? I'm not able to start tests and get the following error: 
`Failed to query the list of test cases in the test bundle: Test bundle not found at: /Users/username/path/build/Build/Products/Debug-iphonesimulator/TestTargetName.xctest`

Thanks in advance

**Comment by plu** [comment]
It depends on `xctool` supporting that. I havn't tried if it does work, but I found this issue, so I'm not sure what's the current state there: https://github.com/facebook/xctool/issues/534

**Comment by plu** [comment]
`xctool` based solution is deprecated, closing this issue because of that fact.
