### ISSUE TITLE
Rake aborted

### ISSUE THREAD

**Issue by allentofight** [plu/parallel_ios_tests#8]
when I run `bundle && rake` 
bundle is success,but rake failed,the fail message is like the following

```shell
rake aborted!
NoMethodError: undefined method `identifier' for nil:NilClass
/Users/ronaldo/.rvm/gems/ruby-2.0.0-p576/gems/simctl-1.1.0/lib/simctl/command/create.rb:13:in `create_device'
/Users/ronaldo/.rvm/gems/ruby-2.0.0-p576/gems/simctl-1.1.0/lib/simctl/command/reset.rb:22:in `reset_device'
/Users/ronaldo/.rvm/gems/ruby-2.0.0-p576/gems/simctl-1.1.0/lib/simctl.rb:22:in `method_missing'
/Users/ronaldo/Desktop/parallel_ios_tests/Rakefile:19:in `block (2 levels) in <top (required)>'
/Users/ronaldo/Desktop/parallel_ios_tests/Rakefile:13:in `block in <top (required)>'
/Users/ronaldo/.rvm/gems/ruby-2.0.0-p576/bin/ruby_executable_hooks:15:in `eval'
/Users/ronaldo/.rvm/gems/ruby-2.0.0-p576/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => default => test
(See full trace by running task with --trace)
```

how to resolve it?

**Comment by plu** [comment]
It looks like you did not have the 9.2 runtime installed. I just merge some changes from @thyrlian - now the project requires the 9.3 runtime.

**Comment by thyrlian** [comment]
@plu maybe it's a good point that you should:
1. tweak the error message a bit?
2. use `SimCtl.Runtime.latest(type)` instead of hardcode any runtime version?

**Comment by allentofight** [comment]
@plu It works! But there is another problem, only one simulator run,the other simulator is launched,but not run simultaneously with the previous one

**Comment by plu** [comment]
@thyrlian good point, thanks, will change it :).

@allentofight I'm pulling `xctool` now from https://github.com/technology-ebay-de/xctool/tree/ebk/release instead. It includes some workaround for hanging on Xcode 7.3.

@allentofight please let me know if this fixes your issue.

**Comment by allentofight** [comment]
@plu Great! It works!Thank you!

**Comment by plu** [comment]
Great! You're welcome :)
